apiVersion: apps/v1
kind: Deployment
metadata:
  name: openedx-lms
  labels:
    app: openedx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: openedx-lms
  template:
    metadata:
      labels:
        app: openedx-lms
    spec:
      containers:
        - name: openedx-lms
          image: openedx/lms:latest
          env:
            - name: MYSQL_HOST
              value: "openedx-mysql.c410yoow65c6.us-east-1.rds.amazonaws.com"
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_USERNAME
              value: "openedx_admin"
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: openedx-secrets
                  key: mysql_password
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: openedx-secrets
                  key: mongodb_uri
            - name: ELASTICSEARCH_HOST
              value: "10.0.102.187"
            - name: REDIS_URL
              value: "redis://openedx-redis.w06qka.0001.use1.cache.amazonaws.com:6379/0"
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: openedx-lms
spec:
  selector:
    app: openedx-lms
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP

