apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-egress-databases
  namespace: openedx
spec:
  podSelector: {}
  egress:
    - ports:
        - protocol: TCP
          port: 3306   # MySQL
        - protocol: TCP
          port: 27017  # MongoDB
        - protocol: TCP
          port: 6379   # Redis
        - protocol: TCP
          port: 9200   # Elasticsearch

