apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: openedx
  namespace: openedx
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  rules:
    - http:
        paths:
          # LMS
          - path: /
            pathType: Prefix
            backend:
              service:
                name: lms
                port:
                  number: 80
          # Studio
          - path: /studio
            pathType: Prefix
            backend:
              service:
                name: studio
                port:
                  number: 80

